package com.gulfemervaaltun.androidgelistirmebootcamp1.odev1

fun main(){
    //değişkenleri tanımladığımız class dan nesne oluşturduk
    val odev= odev1()

    //değerleri ekrana yazdırdık
    println("Sehir: ${odev.sehir}")
    println("Ulke: ${odev.ulke}")
    println("Telefon: ${odev.telefon}")
    println("Posta Kodu: ${odev.posta_kodu}")
    println("Email: ${odev.email}")
    println("Meslek: ${odev.meslek}")
    println("Stok Miktari: ${odev.stok_miktari}")
    println("Musteri Adi: ${odev.musteri_adi}")
    println("Bakiye: ${odev.bakiye}")
    println("Dogum Gunu: ${odev.dogum_gunu}")
    println("Maas: ${odev.maas}")
    println("Medeni Durum: ${odev.medeni_durum}")
    println("Urun Yorumu: ${odev.urun_yorumu}")
    println("Odeme Tarihi: ${odev.odeme_tarihi}")
    println("Odeme: ${odev.odeme}")
    println("Siparis Adeti: ${odev.siparis_adeti}")
    println("Araba Modeli: ${odev.araba_modeli}")
    println("Kitap Adi: ${odev.kitap_adi}")
    println("Yayinlanma Tarihi: ${odev.yayinlanma_tarihi}")
    println("Indirim Miktari: ${odev.indirim_miktari}")
    println("Oda Sayisi: ${odev.oda_sayisi}")
    println("Enlem: ${odev.enlem}")
    println("Boylam: ${odev.boylam}")
    println("Urun Adi: ${odev.urun_adi}")
    println("Yemek Fiyati: ${odev.yemek_fiyati}")
    println("Marka: ${odev.marka}")
    println("Muzik Adi: ${odev.muzik_adi}")
    println("Video Suresi: ${odev.video_suresi}")
    println("Urun Puani: ${odev.urun_puani}")
    println("Resim Adi: ${odev.resim_adi}")
    println("Dosya Formati: ${odev.dosya_formati}")
    println("Renk: ${odev.renk}")
    println("Renk Kodu: ${odev.renk_kodu}")
    println("Telefon Modeli: ${odev.telefon_modeli}")
    println("Ekran Boyutu: ${odev.ekran_boyutu}")
    println("Agirlik: ${odev.agirlik}")
    println("Ulusal Gun: ${odev.ulusal_gun}")
    println("Tatil Gunu: ${odev.tatil_gunu}")
    println("Rezervasyon Tarihi: ${odev.rezervazyon_tarihi}")
    println("Sokak Adi: ${odev.sokak_adi}")
    println("Otobus Hatti: ${odev.otobus_hatti}")
    println("Kalan Dakika: ${odev.kalan_dakika}")
    println("Takip Kodu: ${odev.takip_kodu}")
    println("Kupon Suresi: ${odev.kupon_suresi}")
    println("Kupon Kodu: ${odev.kupon_kodu}")
    println("Fatura Adresi: ${odev.fatura_adresi}")
}